#!/usr/bin/python3

import utils


def _key(s):
    if b"-" in s:
        return s.split(b"-")[1]
    return s
win_names = list(utils.names2tag.keys())
win_names.sort(key=_key)
win_name = utils.run_dmenu(win_names, b"-l", b"100")
tag = utils.names2tag.get(win_name)
if tag:
    utils.hc("use", tag)
